### ISSUE TITLE
Using const instead of var

### ISSUE THREAD

**Issue by Ryuno-Ki** [sachinsancheti1/json-yaml-front-matter#2]
Hi @sachinsancheti1!
Over in the eleventy repo you mentioned, that you'd accept feedback on this repo (even if your CONTRIBUTING.md tells otherwise).

Here comes mine :-)

From what I can tell, those variables aren't reassigned, so you could use `const` instead of `var`:

https://github.com/sachinsancheti1/json-yaml-front-matter/blob/9e0efe4e4c1fb0b3834de0f14db622fba15a378b/templateMaker/js-yaml-script.js#L6-L7

https://github.com/sachinsancheti1/json-yaml-front-matter/blob/9e0efe4e4c1fb0b3834de0f14db622fba15a378b/templateMaker/js-yaml-script.js#L12-L13

**Comment by sachinsancheti1** [comment]
Made the chance in the contribution to just a simple line. I also don't have a licence as I still do not understand that. A recommended license also may be added if you may suggest one.

**Comment by Ryuno-Ki** [comment]
I'd suggest to use GitHub's https://choosealicense.com/ to pick one.

**Comment by sachinsancheti1** [comment]
Change made and license added
