### ISSUE TITLE
Prefer async over sync code execution

### ISSUE THREAD

**Issue by Ryuno-Ki** [sachinsancheti1/json-yaml-front-matter#3]
I know, it is meant as script, but in
https://github.com/sachinsancheti1/json-yaml-front-matter/blob/9e0efe4e4c1fb0b3834de0f14db622fba15a378b/templateMaker/js-yaml-script.js#L6
you're calling code synchronously. A better way would be to put the logic inside a `function` and call it afterwards.

By using [es6-promisify](https://www.npmjs.com/package/es6-promisify) you could turn `fs.readFile` into a Promise-based API. By using an `async function` you could then use `await` to read the file.

The code could look akin to this:

```js
const defaultFilePath = '_site/_data/properties.json';
let outputFileName = 'rename-me';

async function makeTemplate () {
  const properties = await readAsJson(defaultFilePath);

  if (!properties.message) {
    return writeFile(properties);
  } else {
    console.log(properties.message);
  }
}

async function readAsJson (filePath) {
  const jsonData = await fs.readFile(filePath, 'utf8');
  return = JSON.parse(jsonData)[0];  // This could potentially fail!
}

function writeFile (properties) {
  const output = computeOutput(properties);
  outputFileName = getOutputFileName(properties);

  try {
    return fs.writeFile(outputFileName, output, 'utf8');
  } catch (reason) {
    console.error('An error occured while writing JSON Object to file.');
    return console.error(reason);
  }
}

function computeOutput (properties) {
  const frontmatter = yaml.safeDump(properties);
  return `---\n${yamlStr}\n---`;
}

function getOutputFileName (properties) {
  return `_site/houses-for-sale/${properties.websiteLink}.md`
}

makeTemplate();
```

**Comment by sachinsancheti1** [comment]
Hi. Thank you for the insight. The code looks better too this way. Please do PR the same. This is good learning for me

**Comment by sachinsancheti1** [comment]
Hi, I have added a commit. I do not know how to debug and check async functions though the function structure seems right. Please do have a look at the new commit and file added.

**Comment by Ryuno-Ki** [comment]
Am I right in assuming, that you refer to https://github.com/sachinsancheti1/json-yaml-front-matter/commit/fce88d266c980ae6b3b6f1607d39dc8a8766e372 ?

Will comment on that commit then (I think, there are one or two small mistakes in it - so it would've been better with opening a PR)

**Comment by sachinsancheti1** [comment]
thank you.

**Comment by Ryuno-Ki** [comment]
See my comments there.

**Comment by sachinsancheti1** [comment]
https://github.com/sachinsancheti1/json-yaml-front-matter/commit/2192c1aefb50c638e6815532bde7e0a57fb69868 Closed here
